 repos:
   - repo: https://github.com/pycqa/flake8.git
     rev: 4.0.0
     hooks:
       - id: flake8
         args: ['--max-line-length=120', '--per-file-ignores=__init__.py:F401']
   - repo: https://github.com/PyCQA/isort.git
     rev: 4.3.21
     hooks:
       - id: isort
   - repo: https://github.com/pre-commit/mirrors-yapf.git
     rev: v0.30.0
     hooks:
       - id: yapf
   - repo: https://github.com/pre-commit/pre-commit-hooks.git
     rev: v3.1.0
     hooks:
       - id: trailing-whitespace
       - id: check-yaml
       - id: end-of-file-fixer
       - id: requirements-txt-fixer
       - id: double-quote-string-fixer
       - id: check-merge-conflict
       - id: fix-encoding-pragma
       - id: mixed-line-ending
